version: '3'
services:
  nginx:
    network_mode: host
    image: nginx:mainline
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./certs/:/usr/share/certs/"
      - "./:/usr/share/nginx/html"